import "./globals.css";
import Providers from "./providers";
import type { Metadata } from "next";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";
import { cookies } from "next/headers";
import * as cookie from "cookie";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  let username = null;
  const cookieStore = await cookies();
  const c = cookieStore.get("jwt");
  const headers = new Headers();
  headers.set("cookie", cookie.serialize("token", c?.value ?? ""));
  const userResponse = await fetch(
    `${process.env.BASE_URL}/users/me`,
    {
      headers,
    }
  );
  if (userResponse.ok) {
    username = (await userResponse.json()).username;
  }
  return (
    <html lang="en">
      <body className={`antialiased bg-slate-700`}>
        <Providers>
          <ReactQueryDevtools initialIsOpen={false} />
          <nav className="flex flex-row justify-end gap-4 p-4 bg-slate-800 text-white mb-4">
            <Link href="/">Home</Link>
            {username ? (
              <>
                <p>Welcome {username}</p>
                <Link href="/saved">Saved</Link>
                <Link href="/logout">Logout</Link>
              </>
            ) : (
              <>
                <Link href="/login">Login</Link>
                <Link href="/register">Register</Link>
              </>
            )}
          </nav>
          {children}
        </Providers>
      </body>
    </html>
  );
}
